# permissions for end users to view stacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stack-viewer-role
rules:
- apiGroups:
  - cloudformation.linki.space
  resources:
  - stacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudformation.linki.space
  resources:
  - stacks/status
  verbs:
  - get
